# Dates
# The max date is not included in the range
dates:
  min: 2024-06-25
  max: 2024-06-26

# Lines
# If you want equal probabilities set probabilities equal to {} like with the tsps
# If you don't want noise, just remove the noise_std key
lines:
  probabilities:
    '03131': 0.35
    '02561': 0.15
    '06305': 0.15
    '03162': 0.35
  noise_std: 0.05

# Train service providers
# If you want different probabilities explicitly set them here like with the lines
tsps:
  probabilities: {}

# Time slots
# For each day of the week, a different distribution can be set
time_slots:
  probabilities:
    - id: 1
      distribution: hourly
      distribution_kwargs:
        '0': 0
        '1': 0
        '2': 0
        '3': 0
        '4': 0
        '5': 0.02
        '6': 0.06
        '7': 0.08
        '8': 0.10
        '9': 0.06
        '10': 0.04
        '11': 0.04
        '12': 0.03
        '13': 0.03
        '14': 0.05
        '15': 0.07
        '16': 0.05
        '17': 0.08
        '18': 0.10
        '19': 0.08
        '20': 0.05
        '21': 0.03
        '22': 0.02
        '23': 0.01
    - id: 2
      distribution: poisson
      distribution_kwargs:
        mu: 14
  days:
    'Monday': 1
    'Tuesday': 1
    'Wednesday': 1
    'Thursday': 1
    'Friday': 1
    'Saturday': 2
    'Sunday': 2

# Rolling stocks
# The first tsp has explicit probabilities, the second one has equal probabilities
rolling_stocks:
  probabilities:
    '1':
      '1': 0.4
      '2': 0.2
      '3': 0.2
      '4': 0.1
      '5': 0.1
    '2': {}

# Prices
# The base price is generated by the probabilities distribution according to the day of the week
# Then, factors are multiplied to the base price generated by the probabilities distribution
# The distance_factor is multiplied to the distance in km and then added to the base price
prices:
  min: 7
  max: 150
  distance_factor: 0.01
  station_factor:
    '60000': 1.5
    '04040': 1.1
    '71801': 1.3
    default: 1
  line_factor:
    '03131': 1.1
    '02561': 1.05
    default: 1
  time_slot_factor:
    '5': 0.7
    '6': 0.9
    '7': 1
    '8': 1.2
    '9': 1.2
    '10': 1.1
    '11': 1.1
    '12': 1
    '13': 1
    '14': 1
    '15': 1.05
    '16': 1
    '17': 1.05
    '18': 1.1
    '19': 1
    '20': 0.9
    '21': 0.8
    '22': 0.7
    '23': 0.6
    default: 0.5
  tsp_factor:
    '1': 1.2
    '2': 1.1
    default: 1
  seat_factor:
    '1': 1
    '2': 1.33
    default: 1
  probabilities:
    - id: 1
      distribution: gamma
      distribution_kwargs:
        a: 20
        scale: 1
    - id: 2
      distribution: norm
      distribution_kwargs:
        loc: 40
        scale: 10
  days:
    'Monday': 1
    'Tuesday': 1
    'Wednesday': 1
    'Thursday': 1
    'Friday': 1
    'Saturday': 2
    'Sunday': 2
